version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: nalgebra
    versions:
    - 0.24.1
    - 0.25.0
    - 0.25.1
    - 0.25.2
    - 0.25.3
    - 0.25.4
    - 0.26.0
    - 0.26.1
  - dependency-name: crossbeam-channel
    versions:
    - 0.5.0
