[package]
name = "amethyst_rendy"
version = "0.10.1"
authors = []
edition = "2018"
description = "High-level rendering engine with multiple backends"
keywords = ["game", "engine", "renderer", "3d", "amethyst"]
categories = ["rendering", "rendering::engine"]

[features]
dx12 = ["rendy/dx12"]
metal = ["rendy/metal"]
vulkan = ["rendy/vulkan"]
nightly = ["shred/nightly"]
profiler = []

[dependencies]
amethyst_assets = { path = "../amethyst_assets", version = "0.6" }
amethyst_core = { path = "../amethyst_core", version = "0.5" }
amethyst_derive = { path = "../amethyst_derive", version = "0.3" }
amethyst_error = { path = "../amethyst_error", version = "0.1" }
amethyst_window = { path = "../amethyst_window", version = "0.1" }
failure = "0.1"
genmesh = "0.6"
glsl-layout = "0.3"
hibitset = "0.5.4"
lazy_static = "1.0"
log = "0.4"
palette = { version = "0.4", features = ["serde"] }
rendy = { git = "https://github.com/valkum/rendy.git", rev ="7e1f3a7ab986a7e12ac5766d30a118d36f44df3f", features = ["full", "empty", "serde-1"] }
# rendy = { path = "../../rendy/rendy/", features = ["full", "empty", "serde-1"] }
ron = "0.4"
serde = { version = "1", features = ["serde_derive"] }
shred = { version = "0.7"  }
shred-derive = { version = "0.5" }  
fnv = "1"
derivative = "1.0.2"
smallvec = "0.6.9"